version: "3.8"

services:

  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "halal_db"
      POSTGRES_USER: "halal"
      POSTGRES_PASSWORD: "halal_12345678_05"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    depends_on:
      - postgres_db
    ports:
      - "8001:8001"
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn -b 0.0.0.0:8001 HalalBackend.wsgi --reload"
    volumes:
      - .:/app
      - ./static:/app/static/
      - ./media:/app/media/

  nginx:
    image: nginx
    restart: always
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/static/
      - ./media:/usr/media/
    ports:
      - "80:80"

volumes:
  postgres_data: