# Generated by Django 3.2.7 on 2021-10-07 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(related_name='favorite_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
