# Generated by Django 3.2.8 on 2021-10-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Логотип категории'),
        ),
    ]
