# Generated by Django 3.2.7 on 2021-09-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Код')),
                ('title', models.TextField(verbose_name='Описание')),
                ('type', models.CharField(choices=[('Халал', 'good'), ('Сомнительно', 'doubt'), ('Харам', 'harm')], max_length=100, verbose_name='Тип')),
                ('damage_description', models.TextField(verbose_name='Вредность')),
                ('useful_description', models.TextField(verbose_name='Полезность')),
                ('use_description', models.TextField(verbose_name='Использование')),
            ],
            options={
                'verbose_name': 'Код',
                'verbose_name_plural': 'Е коды',
            },
        ),
    ]
