# Generated by Django 3.2.8 on 2021-10-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_time', models.TimeField(verbose_name='Фаджр')),
                ('second_time', models.TimeField(verbose_name='Восход')),
                ('third_time', models.TimeField(verbose_name='Зухр')),
                ('fourth_time', models.TimeField(verbose_name='Аср')),
                ('fifth_time', models.TimeField(verbose_name='Магриб')),
                ('seventh_time', models.TimeField(verbose_name='Иша')),
                ('sixth_time', models.TimeField(verbose_name='Тахажжуд')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Дата и Время',
                'verbose_name_plural': 'Даты и Времена',
            },
        ),
    ]
